# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lptcc-peek-usersv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://lptccapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8376e914e51d450a98c8231b8a1c42a0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9226d09a0d184c55b61520cc0e0c7174 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8376e914e51d450a98c8231b8a1c42a0 }}/userserviceapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lptcc-peek-usersv'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f9a05c3bd354fb1837092829aabacb4 }}
        images: 'lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8376e914e51d450a98c8231b8a1c42a0 }}/userserviceapi:${{ github.sha }}'