# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lptcc-peek-usersv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://lptccapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e7fe3ee8a2a440ae8fe5580e9f9afa87 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e978f0095024a289f05e2a830f22167 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e7fe3ee8a2a440ae8fe5580e9f9afa87 }}/lptccapi/userserviceapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lptcc-peek-usersv'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_072d0a5e5d594753bf3026ffc36d27e8 }}
        images: 'lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e7fe3ee8a2a440ae8fe5580e9f9afa87 }}/lptccapi/userserviceapi:${{ github.sha }}'